### PR TITLE
add masonite

### LINKED ISSUE #304: Masonite
Hey,

I will be implementing the backend with [Masonite](https://github.com/MasoniteFramework/masonite). Masonite is the Modern And Developer Centric Python Web Framework.

Repo: https://github.com/vaibhavmule/masonite-realworld-example-app

### PR DESCRIPTION
**Pull request by vaibhavmule**
fixes #304

### CODE REVIEW

**Comment by mvila** [comment]
Thanks, @vaibhavmule!

Apologies for the delay in reviewing your PR, the maintenance team had very limited availability and we've recruited new members to help with the project.

Your PR is now merged and your frontend implementation should soon appear in the README.

**Comment by vaibhavmule** [comment]
It's backend implementation!

**Comment by mvila** [comment]
Oops, sorry, I made a stupid copy/paste mistake. Don't worry, your implementation will be correctly listed in the backend category.

**Comment by vaibhavmule** [comment]
Also it is complete, not work in progress?

**Comment by mvila** [comment]
Be a little bit more patient, please. The README is autogenerated once a day.

**Comment by vaibhavmule** [comment]
👍

**Pull request merged**
