### PR TITLE
Add Fullstack section and description

### LINKED ISSUE #150: Should We Add An Isomorphic Framework Category?
Should we add a category that frameworks like [Meteor](https://www.meteor.com/) have a spot on the README? 

I personally like the idea but am curious of everyone else's thoughts. @gothinkster/realworld-admins

### PR DESCRIPTION
**Pull request by anishkny**
Just to see what it could look like

Would close #150

### CODE REVIEW

**Comment by Cameron-C-Chapman** [comment]
Looks good to me @anishkny! What do you think @EricSimons?

**Comment by EricSimons** [comment]
I dig it!! Sorry I've been MIA lately, will be swooping in here tmrw to take care of stuff :)

**Comment by anishkny** [comment]
Thanks please reword as appropriate!

**Comment by EricSimons** [comment]
Just changed it so the description was a bit shorter and under the fullstack section (I think it makes more sense there) - would love to hear everyone's thoughts!

**Comment by anishkny** [comment]
LGTM!

**Pull request merged**
