### PR TITLE
feat: add Preact X

### LINKED ISSUE #169: Preact
## Current Status
Codebase in progress: [Codebase](https://github.com/hassanbazzi/preact-realworld-example-app)

Interested in helping out? Say hello! 🎉 [Preact Slack](https://preact-slack.now.sh/)

## Todo:
- [x] 🏁 Fork the starter repo & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@EricSimons)
- [ ] 🔨 Implement all of Conduit's functionality per the spec & API
- [ ] 👀 Peer review of final codebase by RealWorld admins & community (RFC)
- [ ] 🎉 Tag v1 release, move repo to main org, and officially list it on the README!

I have began working on this. :) I will most likely be using [unistore](https://github.com/developit/unistore) for state. And sine Preact is all about performance and low file size, I'm going to see if I can shrink down the styles provided by the project.

### PR DESCRIPTION
**Pull request by mutoe**
The original author was not updated, and I created a version using Preact X.

close #169

### CODE REVIEW

**Comment by mutoe** [comment]
Hello, can you let me know if you have any questions?

**Comment by anishkny** [comment]
Will take a look soon.

**Comment by mutoe** [comment]
I've fixed it, please take a look at it. :)

**Comment by mvila** [comment]
Hi, @mutoe!

I guess the `title` in `etc/frontend-repos.yaml` should be `Preact` instead of `React X`. Could you fix that, please?

**Comment by mutoe** [comment]
@mvila Thanks for your reminder. I have fixed it already.

**Comment by mvila** [comment]
Thanks, @mutoe. I merged your PR. The README should be autogenerated within 24 hours.

**Pull request merged**
