### PR TITLE
Add Pure Go Backend

### LINKED ISSUE #451: Pure Go Backend
Hi Everyone,

I'm writing **realworld** backend in [Golang](https://golang.org/) without any external library.

It's going to be a simple and clean code.

[nasermirzaei89/realworld-go](https://github.com/nasermirzaei89/realworld-go)

It maybe has some bugs. but it tested with postman script.

It's open to any feedback, suggestion and pull requests.

### PR DESCRIPTION
**Pull request by nasermirzaei89**
Closes #451

### CODE REVIEW

**Comment by mvila** [comment]
Hi, @nasermirzaei89!

Apologies for the delay in reviewing your PR, the maintenance team had very limited availability and we've recruited new members to help with the project.

Thanks for your pure Go implementation. 😄 So, you don't use any database?

**Comment by nasermirzaei89** [comment]
Hi @mvila
It's hard to remember what I did 😬 
But I used an interface for databases, and just implemented an in-memory version.

**Comment by mvila** [comment]
So, every time you restart the backend, all the data is lost? I am sorry, but I don't think we can qualify that as a "real world" backend! 😄

**Comment by nasermirzaei89** [comment]
I should add a persist repository and then I tell you to review it. Thanks!

**Comment by mvila** [comment]
OK, @nasermirzaei89. 😄

I close this PR. Please create a new PR when you want to submit your implementation again.

**Pull request closed without merging**
