### PR TITLE
feat: add tags & add lost operationId & refactoring components

### PR DESCRIPTION
**Pull request by kainsk**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/gothinkster/realworld/blob/master/CONTRIBUTING.md#commit

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- added .vscode/ to gitinmore
- added operationId for "Get Tags"
- added tags globaly

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by kainsk** [comment]
linter - VACUUM:

- **FROM** (quality - 10%)  https://api.quobix.com/report?url=https://github.com/gothinkster/realworld/blob/1f6218f4f8bff1ac9102b23f8ed68501e3cb7cbc/api/openapi.yml
- **TO** (quality - 58%) https://api.quobix.com/report?url=https://raw.githubusercontent.com/kainsk/realworld/80b2d1e9554c9c0d41daa450b97424e0a56d65aa/api/openapi.yml

maybe need add examples to responses, but I not shure...

**Comment by geromegrignon** [comment]
Hi @kainsk, thanks for your contribution.
Feel free to ping me once it's ready for the review :)

**Comment by kainsk** [comment]
> Hi @kainsk, thanks for your contribution. Feel free to ping me once it's ready for the review :)

Oh, i'm sorry.

- ping!

**Comment by kainsk** [comment]
Hi! @geromegrignon ping)

**Comment by geromegrignon** [comment]
Hi @kainsk, merged!
Thanks so much for this contribution.

**Pull request merged**
