### PR TITLE
Add Android(Kotlin) in mobile-repo

### PR DESCRIPTION
**Pull request by Marvel999**
Add Android(Kotlin) example project link please review and merge into the master repo.

### CODE REVIEW

**Comment by Marvel999** [comment]
conflict resolve

**Review by murakobardenas — APPROVED** [review]

**Comment by Marvel999** [comment]
Please Help Me And Point out the issue So I can resolve it.

**Comment by geromegrignon** [comment]
as we are moving the list of implementations to https://codebase.show/projects/realworld and your project has been added there, i'm closing this PR.
Thanks for your contribution!

**Comment by Marvel999** [comment]
Welcome, sir.

**Pull request closed without merging**
