### PR TITLE
Update dojo2 references to dojo

### PR DESCRIPTION
**Pull request by agubler**
Updates references to "Dojo 2", to plain "Dojo" (as Dojo is on version 6 now 😄)

### CODE REVIEW

**Comment by agubler** [comment]
@anishkny Thanks for adding the label - I've updated for the conflicts, would be good to get this reviewed.

**Comment by agubler** [comment]
Hello all, if I update the conflicts again, do you think we can get this merged?

**Comment by agubler** [comment]
Hey @anishkny is this something that we can get merged (if I update the conflicts)?

**Comment by agubler** [comment]
@anishkny bump, if I update the PR can we get this merged?

**Comment by mvila** [comment]
Thanks, @agubler!

Apologies for the delay in reviewing your PR, the maintenance team had very limited availability and we've recruited new members to help with the project.

I made the change in #593 and merged it to `master`. The README should be autogenerated within 24 hours.

**Pull request closed without merging**
