### PR TITLE
add React Native

### PR DESCRIPTION
**Pull request by NWylynko**
I believe [my fork of the repo](https://github.com/NWylynko/realworld-react-native) should be pulled into the repo, it uses the latest versions of react, react native and react navigation. It doesn't use any unnecessary dependencies and has been tested on ios and android. I'm not sure how complete of a project you want before adding it to the list but i've got a good chunk of the spec/api implemented and should get it pretty complete by the end of the week. I can get screenshots but there are some pretty up to date screenshots on my pull request into claytonschneider's repo.

### CODE REVIEW

**Comment by EricSimons** [comment]
Hey Nick- is the app fully complete at this point? Happy to review it if so

**Comment by NWylynko** [comment]
Hey Eric, the app is fully complete, everything that can be done on the website can be done through this app. If you have a look at the projects there is a couple things to do but they are not required for the app to work at all.

**Comment by mvila** [comment]
Hi @NWylynko!

Apologies for the delay in reviewing your PR, the maintenance team had very limited availability and we've recruited new members to help with the project.

Could you please activate the "Issues" section in your repo? I'd like to report some problems that I have noticed.

**Comment by NWylynko** [comment]
hey @mvila,

Its all good, I've been busy doing other things. I turned on issues yesterday, but I have spent yesterday and today trying to get the newest version on react native running on my macbook or imac and I cant get it to run as they are just too old to run the latest version of xcode. what this means is I have no way to update and then test the mobile app to get it up and running with the latest version of react native. 

But I can still run the current version so any issues you have I should be able to fix.

Thanks

**Comment by mvila** [comment]
Hi @NWylynko,

I am sorry but I don't think I can approve your implementation for now. First, not being able to update React Native is not good, and second, your code would be more readable if you stick to the JavaScript idioms and conventions.

Example from `src/api/api.js`:

```js
export default class api {
  constructor() {
    this.token;
    // ...
```

- Class names should start with a cap.
- What `this.token` is doing?

Please open a new PR when you are ready to submit your implementation again.

**Pull request closed without merging**
