### PR TITLE
List Anish & Cameron as the Core Maintainers

### PR DESCRIPTION
**Pull request by EricSimons**
@anishkny and @Cameron-C-Chapman have poured so much amazing work into this project over the past few years, and RealWorld would never have grown to this size (nor will it keep growing) without their continued efforts.

While Albert and I spent a lot of time initially getting RW off the ground, our contributions have been slim as of late. As such, I'd like to amend the readme to list Anish & Cameron as the primary/core maintainers of this project. They most certainly deserve it. (Also, it'll help me sleep better 😛)

Anish/Cameron- would you like to do the honors? :)

### CODE REVIEW

**Comment by EricSimons** [comment]
PS- I still plan on being involved with RW! I'm chunking out hours specifically for RW this year, so I'll be hanging out here more frequently <3

**Comment by Cameron-C-Chapman** [comment]
@anishkny has really been doing all that work the last couple of months but I should be able to get back to being more involved and helping him out. I'd be happy to keep helping out going forward.

Thanks @EricSimons 😄

**Comment by EricSimons** [comment]
Awesome to hear Cameron! Sounds like you and I can share the same new years resolution for RW 😝

Btw you two are seriously awesome. I really appreciate y'all stepping up to the plate while I was bogged down w/ founding stackblitz ❤

**Comment by anishkny** [comment]
Oh my god @EricSimons thanks for the kind words! Its been such an enriching experience. And by the way [StackBlitz](https://stackblitz.com) is just mind-blowing!

And of course thanks to the RW community who has often been patient as we try to triage issues/add repos as fast as we can :)

Lets hope we can get into a better cadence for an even more awesome **2019**! 🎉🎉🎉

**Pull request merged**
