### PR TITLE
add Android(Kotlin) to mobile-repos

### PR DESCRIPTION
**Pull request by championswimmer**

### CODE REVIEW

**Comment by championswimmer** [comment]
@EricSimons

**Comment by championswimmer** [comment]
@anishkny

**Comment by geromegrignon** [comment]
Could you update the Readme with the requirements and steps needed to run and test the app?

**Review by kadirselcuk — APPROVED** [review]

**Review by kadirselcuk — APPROVED** [review]

**Comment by geromegrignon** [comment]
As we are moving the list to https://codebase.show/projects/realworld, Please submit your implementation there once your readme has been updated.
Thanks for your contribution.

**Pull request closed without merging**
