### PR TITLE
Updating npm test script to run newman integration tests

### PR DESCRIPTION
**Pull request by Cameron-C-Chapman**
@gothinkster/realworld-admins Any objections to merging this?

### CODE REVIEW

**Comment by brwr** [comment]
Two concerns:

1) I think this would be better offer in base implementation repo. That way users will get it for free when they clone the package. A side effect of this is that it will be included in front-end code as well, so npm test probably isn't the right command to use.

2) To my knowledge, we don't make any guarantees that the backend will be running on port 3000 which is what the Postman collection assumes.

Feel free to correct me if I'm wrong about either of those.

**Comment by Cameron-C-Chapman** [comment]
Those are both good points.

The idea here is that we automate the test of the collection during a build of this repo, not necessarily that the users run this locally. They are using postman and now they have a swagger spec to use for testing locally. This would be about automatically running the tests against incoming pull requests that are updating the collection itself. 

We could work towards making it flexible enough for use with any backend implementation but that wasn't what I was trying to do. The only thing someone would need to do is update the Conduit.postman_integration_test_environment.json file with the correct port if needed. And if we want to make this something everyone could use maybe the name integration_test_environment should be changed to automated_test or something like that?

To the point of not having it under npm test, I agree, I should probably change that. Maybe an `npm run integration-test` or something along those lines?

**Comment by brwr** [comment]
Sounds good to me!

**Comment by Cameron-C-Chapman** [comment]
I moved the integration test script out of the npm test script config and into the .travis.yml script config so it's more specific to ci testing.

**Comment by SandeeshS** [comment]
I'm still not sure if the test should be here instead of the backend where the api is live. This would help us verify the changes to the postman collection, but at the same time every test would fail here if there were changes to the api and we don't make the appropriate changes to the collection in time.

**Comment by Cameron-C-Chapman** [comment]
If this was in place you wouldn't be able to merge changes to the api into master if the collection tests failed. That's the mechanism to make sure the collection always represents the current api.

If you think of it in terms of a v1 api and v2 api, a change to the active v1 api should require an update to the collection. Work on v2 should be in a branch that doesn't affect the current officially supported api. 

That's how I thought of it anyway but I'm open to backing this out if that doesn't seem like the way the workflow should work.

**Comment by SandeeshS** [comment]
@Cameron-C-Chapman guess that works out :+1:  @EricSimons can make the final call

**Comment by EricSimons** [comment]
I dig it — merging now now! 🍻

**Pull request merged**
