### PR TITLE
feat: implementation list moved to codebaseshow

### PR DESCRIPTION
**Pull request by geromegrignon**
remove implementation list
add new maintainers
remove github issues references

### CODE REVIEW

**Comment by cirosantilli** [comment]
Hi Gerome,

I noticed that the top 3 most starred frontends are not present in codebaseshow, e.g.:

-  1: React / Redux: https://github.com/gothinkster/react-redux-realworld-example-app
-  2: Angular https://github.com/gothinkster/angular-realworld-example-app
-  3: Vue https://github.com/gothinkster/vue-realworld-example-app

What's up with those?

Cheers.

**Comment by cirosantilli** [comment]
Edit: I had a better look now, saw they are under unmaintained implementations at the bottom. Might be good to clarify what that means on README of those frontend repos more precisely their state since those are such important frontends (e.g. looking for maintainers? or need complete rewrite? What's broken on them?)

**Comment by geromegrignon** [comment]
Hello @cirosantilli i'm currently working on an official announcement about the maintenance of the project.
As those repositories aren't maintained anymore (over 500 issues/pull requests opened among them), we plan to move to a complete community based list of implementations rather than trying to keep them up to date (as it already failed once).
Why ? They aren't broken and as they are working fine, they would fit 'production' requirements. But as the goal of the project is to be able to compare quickly how to implement specs with different language/frameworks, it implies we should provide implementations with up to date versions. When you are about to discover a new language/framework, you want to see how it works now, not how it worked few versions ago. For some implementations, it might introduces breaking changes.

I understand some ongoing decisions might be misleading as still in progress, as we are landing on the project as maintainers we are working on solutions to fix the current situation. There might need some tweaks but we want to make some moves rather than waiting several months before introducing changes.
I should release an issue about the future of the project before the end of the current week.

**Comment by cirosantilli** [comment]
Thanks Gerome,

Yes, I'm also somewhat thinking what would be the ideal setup.

Maybe the optimal solution is to just explicitly list the versions of the libraries used https://codebase.show/projects/realworld , e.g. Express v1.2.3 + sequelize v4.5.6. Then if one project becomes unmaintained, someone will end up adding a port as a separate entry, and that one will eventually win if not merged back.

**Pull request merged**
